# Generated by Django 5.2 on 2025-04-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('months', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('tokens', models.JSONField()),
                ('server_invite', models.CharField(max_length=255)),
                ('server_id', models.IntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RedeemCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('amount', models.IntegerField(default=2)),
                ('months', models.IntegerField(default=1)),
                ('redeemed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tokens', models.JSONField(blank=True, default=dict, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
