# Generated by Django 5.2 on 2025-04-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemcode',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='redeemcode',
            name='server_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redeemcode',
            name='server_invite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
