# Generated by Django 5.2 on 2025-05-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_order_completed_order_service_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='completed',
            field=models.IntegerField(default=0),
        ),
    ]
