# Generated by Django 5.2 on 2025-05-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_order_error_order_message_alter_order_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='server_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
